# Generated by Django 5.2.1 on 2025-06-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='archivee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='notes_admin',
            field=models.TextField(blank=True, verbose_name='Notes administrateur'),
        ),
    ]
