# Generated by Django 5.2.1 on 2025-06-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_archivee_commande_notes_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_livraison_estimee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='numero_suivi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
