# Generated by Django 5.2.1 on 2025-06-18 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_date_livraison_estimee_and_more'),
        ('produits', '0002_alter_pack_options_pack_favoris'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecisionPersonnalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_a_graver', models.TextField(blank=True, help_text='Précisez le texte exact à graver', verbose_name='Texte à graver')),
                ('date_a_graver', models.CharField(blank=True, help_text='Format: JJ/MM/AAAA', max_length=50, verbose_name='Date à graver')),
                ('mot_doux', models.CharField(blank=True, help_text='Maximum 100 caractères', max_length=100, verbose_name='Mot doux personnalisé')),
                ('laisser_choisir_mot_doux', models.BooleanField(default=False, verbose_name='Laissez-nous choisir le mot doux')),
                ('couleur_preference', models.CharField(blank=True, help_text='Précisez votre couleur préférée', max_length=50, verbose_name='Couleur préférée')),
                ('taille_preference', models.CharField(blank=True, help_text='Précisez la taille souhaitée', max_length=50, verbose_name='Taille préférée')),
                ('instructions_speciales', models.TextField(blank=True, help_text='Toute autre précision importante', verbose_name='Instructions spéciales')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('element_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precisions_personnalisation', to='commandes.elementcommande')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.option')),
            ],
            options={
                'verbose_name': 'Précision de personnalisation',
                'verbose_name_plural': 'Précisions de personnalisation',
                'unique_together': {('element_commande', 'option')},
            },
        ),
    ]
