# Generated by Django 5.2.1 on 2025-06-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_profil_email_verifie_connexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='date_demande_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='suppression_demandee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='token_suppression',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
