# Generated by Django 5.2.1 on 2025-06-18 18:36

import django.core.validators
import django.db.models.deletion
import utilisateurs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_profil_date_demande_suppression_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='affichage_anonyme',
            field=models.BooleanField(default=False, verbose_name='Afficher mes avis de manière anonyme'),
        ),
        migrations.AddField(
            model_name='profil',
            name='autoriser_nom_public',
            field=models.BooleanField(default=False, verbose_name="Autoriser l'affichage de mon nom complet dans les avis"),
        ),
        migrations.AddField(
            model_name='profil',
            name='date_mariage',
            field=models.DateField(blank=True, null=True, verbose_name='Date de votre mariage'),
        ),
        migrations.AddField(
            model_name='profil',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text='Photo de profil (JPG/PNG, max 5MB)', null=True, upload_to=utilisateurs.models.upload_to_profile, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.CreateModel(
            name='AvisClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (sur 5)')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre de votre avis')),
                ('contenu', models.TextField(help_text='Partagez votre expérience (100-500 caractères)', max_length=500, verbose_name='Votre expérience')),
                ('date_mariage', models.DateField(verbose_name='Date de votre mariage')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de modération'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('afficher_accueil', models.BooleanField(default=False, verbose_name="Afficher sur la page d'accueil")),
                ('commentaire_moderation', models.TextField(blank=True, verbose_name='Commentaire de modération')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_moderation', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL)),
                ('moderateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_moderes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo de mariage (JPG/PNG, max 5MB)', upload_to=utilisateurs.models.upload_to_avis_photos, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende (optionnel)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='utilisateurs.avisclient')),
            ],
            options={
                'verbose_name': "Photo d'avis",
                'verbose_name_plural': "Photos d'avis",
                'ordering': ['ordre'],
            },
        ),
    ]
