# Generated by Django 5.2.1 on 2025-06-20 00:25

import django.core.validators
import django.db.models.deletion
import rh_gestion.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Salaire mensuel (FCFA)')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('conge', 'En congé'), ('arret', 'Arrêt de travail'), ('suspendu', 'Suspendu'), ('demission', 'Démission'), ('licencie', 'Licencié'), ('retraite', 'Retraité')], default='actif', max_length=20, verbose_name="Statut de l'employé")),
                ('photo', models.ImageField(blank=True, null=True, upload_to=rh_gestion.models.upload_to_employee_photos, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name="Photo de l'employé")),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('ville', models.CharField(default='Bamako', max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='Mali', max_length=100, verbose_name='Pays')),
                ('notes', models.TextField(blank=True, verbose_name='Notes et observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('paternite', 'Congé paternité'), ('exceptionnel', 'Congé exceptionnel'), ('formation', 'Congé formation'), ('sans_solde', 'Congé sans solde')], max_length=20, verbose_name='Type de congé')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut de la demande')),
                ('motif', models.TextField(verbose_name='Motif de la demande')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaire_validation', models.TextField(blank=True, verbose_name='Commentaire de validation')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='rh_gestion.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='ArretTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('motif', models.TextField(verbose_name='Motif médical')),
                ('justificatif', models.FileField(upload_to=rh_gestion.models.upload_to_justificatifs, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Justificatif médical')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_declaration', models.DateTimeField(auto_now_add=True, verbose_name='Date de déclaration')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets_travail', to='rh_gestion.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Arrêt de travail',
                'verbose_name_plural': 'Arrêts de travail',
                'ordering': ['-date_declaration'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du poste')),
                ('departement', models.CharField(choices=[('direction', 'Direction Générale'), ('administration', 'Administration Générale'), ('comptabilite', 'Comptabilité et Finances'), ('it', 'IT / Développement Web'), ('commercial', 'Ventes / Commercial'), ('marketing', 'Marketing'), ('communication', 'Communication'), ('service_client', 'Service Client'), ('logistique', 'Logistique / Transport'), ('services_generaux', 'Services Généraux'), ('securite', 'Sécurité')], max_length=50, verbose_name='Département')),
                ('description', models.TextField(blank=True, verbose_name='Description du poste')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Poste actif')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['departement', 'nom'],
                'unique_together': {('nom', 'departement')},
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='rh_gestion.poste', verbose_name='Poste occupé'),
        ),
        migrations.CreateModel(
            name='FicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Salaire de base (FCFA)')),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Primes et indemnités (FCFA)')),
                ('retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Retenues et cotisations (FCFA)')),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Salaire net (FCFA)')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('pdf', models.FileField(blank=True, null=True, upload_to=rh_gestion.models.upload_to_fiches_paie, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fiche de paie PDF')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='rh_gestion.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'verbose_name_plural': 'Fiches de paie',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
    ]
