# Generated by Django 5.2.1 on 2025-05-20 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('couleur', 'Couleur'), ('matiere', 'Matière'), ('taille', 'Taille'), ('style', 'Style'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.CharField(choices=[('standard', 'Standard'), ('prestige', 'Prestige'), ('luxe', 'Luxe')], max_length=20)),
                ('image_principale', models.ImageField(blank=True, upload_to='packs/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pack',
                'verbose_name_plural': 'Packs',
                'ordering': ['categorie', 'prix'],
            },
        ),
        migrations.CreateModel(
            name='ImagePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packs/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('est_principale', models.BooleanField(default=False)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produits.pack')),
            ],
            options={
                'verbose_name': 'Image du pack',
                'verbose_name_plural': 'Images des packs',
            },
        ),
        migrations.CreateModel(
            name='OptionDePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_supplement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.option')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='produits.pack')),
            ],
            options={
                'verbose_name': 'Option de pack',
                'verbose_name_plural': 'Options de pack',
                'unique_together': {('pack', 'option')},
            },
        ),
    ]
