# Generated by Django 5.2.1 on 2025-05-26 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={'ordering': [models.Case(models.When(categorie='standard', then=models.Value(1)), models.When(categorie='prestige', then=models.Value(2)), models.When(categorie='luxe', then=models.Value(3)), default=models.Value(4)), 'prix'], 'verbose_name': 'Pack', 'verbose_name_plural': 'Packs'},
        ),
        migrations.AddField(
            model_name='pack',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='packs_favoris', to=settings.AUTH_USER_MODEL),
        ),
    ]
